import os
import numpy as np
import pandas as pd
import torch
from torch.utils.data import Dataset
from utils.mypath import MyPath


class WADI(Dataset):
    """`WADI` Dataset.
    Args:
        root (string): Root directory of dataset.
        train (bool): If True, loads training data; otherwise loads test data.
        transform (callable, optional): Optional transform.
        mean_data, std_data: Normalization stats (must be passed for test set).
    """
    base_folder = ''

    def __init__(self, fname, root=MyPath.db_root_dir('wadi'), train=True,
                 transform=None, sanomaly=None, mean_data=None, std_data=None):

        super(WADI, self).__init__()

        # Allow override via environment variable (used by run_wadi.py on Kaggle)
        if 'wadi_DATASET_PATH' in os.environ:
            root = os.environ['wadi_DATASET_PATH']

        self.root = root
        self.transform = transform
        self.sanomaly = sanomaly
        self.train = train
        self.classes = ['Normal', 'Anomaly']

        self.data = []
        self.targets = []
        wsz, stride = 512, 200

        if self.train:
            # ------------------------------------------------------------------
            # Train file: WADI_14days_new.csv
            # Format: Row, Date, Time, sensor1..sensorN   (NO label column)
            # ------------------------------------------------------------------
            file_path = os.path.join(self.root, "WADI_14days_new.csv")
            df = pd.read_csv(file_path, low_memory=False)
            df.columns = df.columns.str.strip()

            # Drop non-sensor columns
            drop_cols = ['Row', 'Date', 'Time']
            df = df.drop(columns=[c for c in drop_cols if c in df.columns], errors='ignore')

            # Force all remaining columns to numeric (coerce bad values to NaN)
            df = df.apply(pd.to_numeric, errors='coerce')
            # Drop columns that are entirely NaN after coercion
            df = df.dropna(axis=1, how='all')

            temp = df.values.astype(np.float32)
            labels = np.zeros(len(temp), dtype=np.int64)

        else:
            # ------------------------------------------------------------------
            # Test file: WADI_attackdataLABLE.csv
            # Row 0 : 0, 1, 2, ...  (fake header generated by bad export)
            # Row 1 : Row, Date, Time, ..., "Attack LABLE (1:No Attack, -1:Attack)"
            # Row 2+ : actual data
            # ------------------------------------------------------------------
            file_path = os.path.join(self.root, "WADI_attackdataLABLE.csv")

            # Read with the first row treated as header (the fake numeric one)
            raw = pd.read_csv(file_path, header=0, low_memory=False)

            # The second row (index 0 after reading) holds the REAL column names
            real_cols = raw.iloc[0].tolist()
            df = raw.iloc[1:].copy()
            df.columns = [str(c).strip() for c in real_cols]
            df = df.reset_index(drop=True)

            # Locate the label column
            label_col = None
            for col in df.columns:
                if 'attack' in col.lower() and 'lable' in col.lower():
                    label_col = col
                    break
            if label_col is None:
                # Fallback: last column
                label_col = df.columns[-1]
                print(f"[WADI] Warning: label column not found, using last column: '{label_col}'")

            # Label mapping: 1 → 0 (Normal), -1 → 1 (Anomaly)
            raw_labels = pd.to_numeric(df[label_col], errors='coerce').fillna(1)
            labels = np.where(raw_labels == 1, 0, 1).astype(np.int64)

            # Drop non-sensor columns
            drop_cols = ['Row', 'Date', 'Time', label_col]
            df = df.drop(columns=[c for c in drop_cols if c in df.columns], errors='ignore')

            # Force all remaining columns to numeric (critical: avoids 0-column issue)
            df = df.apply(pd.to_numeric, errors='coerce')
            # Drop columns that are entirely NaN after coercion
            df = df.dropna(axis=1, how='all')

            temp = df.values.astype(np.float32)

        print(f"[WADI] {'Train' if self.train else 'Test'} shape: {temp.shape}")

        # Handle NaN
        if np.any(np.isnan(temp)):
            print('[WADI] Data contains NaN — replaced with zero')
            temp = np.nan_to_num(temp)

        # Normalization
        self.mean, self.std = mean_data, std_data
        if self.train:
            self.mean = np.mean(temp, axis=0)
            self.std = np.std(temp, axis=0)
            self.std[self.std == 0.0] = 1.0
            temp = (temp - self.mean) / self.std
        else:
            if mean_data is None or std_data is None:
                print("[WADI] Warning: Test loaded without train stats — using self-statistics (may cause leakage).")
                self.mean = np.mean(temp, axis=0)
                self.std = np.std(temp, axis=0)
                self.std[self.std == 0.0] = 1.0
            else:
                self.std = std_data.copy()
                self.std[self.std == 0.0] = 1.0
                self.mean = mean_data

            # Align columns: if test has fewer/more columns than train, trim/pad
            if temp.shape[1] != self.mean.shape[0]:
                print(f"[WADI] Column mismatch: test={temp.shape[1]}, train={self.mean.shape[0]}. Trimming to min.")
                n = min(temp.shape[1], self.mean.shape[0])
                temp = temp[:, :n]
                self.mean = self.mean[:n]
                self.std = self.std[:n]

            temp = (temp - self.mean) / self.std

        self.targets = labels
        self.data = temp
        self.data, self.targets = self.convert_to_windows(wsz, stride)

    def convert_to_windows(self, w_size, stride):
        sam_size = 5
        w_size_eff = w_size * sam_size
        sz = int((self.data.shape[0] - w_size_eff) / stride)
        windows = []
        wlabels = []
        for i in range(sz):
            st = i * stride
            w = self.data[st:st + w_size_eff:sam_size]
            lbl = 1 if self.targets[st:st + w_size_eff].any() else 0
            windows.append(w)
            wlabels.append(lbl)
        return np.stack(windows), np.array(wlabels, dtype=np.int64)

    def __getitem__(self, index):
        ts_org = torch.from_numpy(self.data[index]).float()
        if len(self.targets) > 0:
            target = torch.tensor(int(self.targets[index]), dtype=torch.long)
            class_name = self.classes[target]
        else:
            target = 0
            class_name = ''

        ts_size = (ts_org.shape[0], ts_org.shape[1])
        out = {
            'ts_org': ts_org,
            'target': target,
            'meta': {'ts_size': ts_size, 'index': index, 'class_name': class_name}
        }
        return out

    def get_ts(self, index):
        return self.data[index]

    def get_info(self):
        return self.mean, self.std

    def concat_ds(self, new_ds):
        self.data = np.concatenate((self.data, new_ds.data), axis=0)
        self.targets = np.concatenate((self.targets, new_ds.targets), axis=0)

    def __len__(self):
        return len(self.data)

    def extra_repr(self):
        return "Split: {}".format("Train" if self.train is True else "Test")